# Generated by Django 3.2.11 on 2022-02-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20220202_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='agenda_agendaplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Title', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
