# Generated by Django 3.2.11 on 2022-02-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20220202_1120'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_agendaplugin', serialize=False, to='cms.cmsplugin'),
        ),
    ]
